In [8]:
pip install pycaret

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycaret in /Users/being/Library/Python/3.9/lib/python/site-packages (3.2.0)
Requirement already satisfied: imbalanced-learn>=0.8.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.11.0)
Requirement already satisfied: tbats>=1.1.3 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.1.3)
Requirement already satisfied: numpy<1.27,>=1.21 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.23.1)
Requirement already satisfied: markupsafe>=2.0.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (2.1.3)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.9.2)
Requirement already satisfied: scipy~=1.10.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.10.1)
Requirement already satisfied: plotly>=5.0.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (5.18.0)
Requirement already satisfied: xxhash in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (3.4.1)
Requirement already satisfied: ipywidgets>=7.6.5 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (8.1.1)
Requirement already satisfied: pandas<2.0.0,>=1.3.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.5.3)
Requirement already satisfied: schemdraw==0.15 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.15)
Requirement already satisfied: tqdm>=4.62.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (4.66.1)
Requirement already satisfied: category-encoders>=2.4.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (2.6.3)
Requirement already satisfied: pyod>=1.0.8 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.1.2)
Requirement already satisfied: scikit-plot>=0.3.7 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.3.7)
Requirement already satisfied: ipython>=5.5.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (8.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.14.1)
Requirement already satisfied: yellowbrick>=1.4 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.5)
Requirement already satisfied: wurlitzer in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (3.0.3)
Requirement already satisfied: jinja2>=1.2 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (3.1.2)
Requirement already satisfied: importlib-metadata>=4.12.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (6.0.0)
Requirement already satisfied: numba>=0.55.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.58.1)
Requirement already satisfied: psutil>=5.9.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (5.9.4)
Requirement already satisfied: scikit-learn<1.3.0,>=1.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.2.2)
Requirement already satisfied: kaleido>=0.2.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.2.1)
Requirement already satisfied: deprecation>=2.1.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (2.1.0)
Requirement already satisfied: cloudpickle in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (3.0.0)
Requirement already satisfied: matplotlib<=3.6,>=3.3.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (3.6.0)
Requirement already satisfied: lightgbm>=3.0.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (4.2.0)
Requirement already satisfied: pmdarima!=1.8.1,<3.0.0,>=1.8.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (2.0.4)
Requirement already satisfied: nbformat>=4.2.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (5.7.0)
Requirement already satisfied: requests>=2.27.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (2.31.0)
Requirement already satisfied: joblib>=1.2.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (1.3.2)
Requirement already satisfied: sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pycaret) (0.21.1)
Requirement already satisfied: patsy>=0.5.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from category-encoders>=2.4.0->pycaret) (0.5.6)
Requirement already satisfied: packaging in /Users/being/Library/Python/3.9/lib/python/site-packages (from deprecation>=2.1.0->pycaret) (23.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from imbalanced-learn>=0.8.1->pycaret) (3.2.0)
Requirement already satisfied: zipp>=0.5 in /Users/being/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=4.12.0->pycaret) (3.15.0)
Requirement already satisfied: jedi>=0.16 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (0.18.2)
Requirement already satisfied: traitlets>=5 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (5.9.0)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (3.0.38)
Requirement already satisfied: backcall in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: pickleshare in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: matplotlib-inline in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pygments>=2.4.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (2.14.0)
Requirement already satisfied: appnope in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (0.1.3)
Requirement already satisfied: pexpect>4.3 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (4.8.0)
Requirement already satisfied: decorator in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: stack-data in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipython>=5.5.0->pycaret) (0.6.2)
Requirement already satisfied: jupyterlab-widgets~=3.0.9 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.9)
Requirement already satisfied: comm>=0.1.3 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipywidgets>=7.6.5->pycaret) (0.2.1)
Requirement already satisfied: widgetsnbextension~=4.0.9 in /Users/being/Library/Python/3.9/lib/python/site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.9)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: python-dateutil>=2.7 in /Users/being/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (2.8.2)
Requirement already satisfied: pillow>=6.2.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (10.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (3.1.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (1.4.5)
Requirement already satisfied: contourpy>=1.0.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /Users/being/Library/Python/3.9/lib/python/site-packages (from matplotlib<=3.6,>=3.3.0->pycaret) (0.11.0)
Requirement already satisfied: jsonschema>=2.6 in /Users/being/Library/Python/3.9/lib/python/site-packages (from nbformat>=4.2.0->pycaret) (4.19.2)
Requirement already satisfied: jupyter-core in /Users/being/Library/Python/3.9/lib/python/site-packages (from nbformat>=4.2.0->pycaret) (5.2.0)
Requirement already satisfied: fastjsonschema in /Users/being/Library/Python/3.9/lib/python/site-packages (from nbformat>=4.2.0->pycaret) (2.18.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/being/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/being/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.10.6)
Requirement already satisfied: attrs>=22.2.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (23.1.0)
Requirement already satisfied: llvmlite<0.42,>=0.41.0dev0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from numba>=0.55.0->pycaret) (0.41.1)
Requirement already satisfied: pytz>=2020.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pandas<2.0.0,>=1.3.0->pycaret) (2023.3.post1)
Requirement already satisfied: six in /Users/being/Library/Python/3.9/lib/python/site-packages (from patsy>=0.5.1->category-encoders>=2.4.0->pycaret) (1.16.0)
Requirement already satisfied: ptyprocess>=0.5 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pexpect>4.3->ipython>=5.5.0->pycaret) (0.7.0)
Requirement already satisfied: tenacity>=6.2.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from plotly>=5.0.0->pycaret) (8.2.3)
Requirement already satisfied: dash>=2.9.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from plotly-resampler>=0.8.3.1->pycaret) (2.14.1)
Requirement already satisfied: orjson<4.0.0,>=3.8.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from plotly-resampler>=0.8.3.1->pycaret) (3.9.10)
Requirement already satisfied: tsdownsample==0.1.2 in /Users/being/Library/Python/3.9/lib/python/site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.2)
Requirement already satisfied: typing-extensions>=4.1.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (4.5.0)
Requirement already satisfied: Werkzeug<3.1 in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.7)
Requirement already satisfied: dash-html-components==2.0.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: Flask<3.1,>=1.0.4 in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.3.3)
Requirement already satisfied: setuptools in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (68.2.2)
Requirement already satisfied: dash-table==5.0.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (5.0.0)
Requirement already satisfied: retrying in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.3.4)
Requirement already satisfied: ansi2html in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.8.0)
Requirement already satisfied: nest-asyncio in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.5.6)
Requirement already satisfied: dash-core-components==2.0.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.0.0)
Requirement already satisfied: itsdangerous>=2.1.2 in /Users/being/Library/Python/3.9/lib/python/site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (2.1.2)
Requirement already satisfied: click>=8.1.3 in /Users/being/Library/Python/3.9/lib/python/site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in /Users/being/Library/Python/3.9/lib/python/site-packages (from Flask<3.1,>=1.0.4->dash>=2.9.0->plotly-resampler>=0.8.3.1->pycaret) (1.6.2)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (3.0.5)
Requirement already satisfied: urllib3 in /Users/being/Library/Python/3.9/lib/python/site-packages (from pmdarima!=1.8.1,<3.0.0,>=1.8.0->pycaret) (1.26.16)
Requirement already satisfied: wcwidth in /Users/being/Library/Python/3.9/lib/python/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/being/Library/Python/3.9/lib/python/site-packages (from requests>=2.27.1->pycaret) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/being/Library/Python/3.9/lib/python/site-packages (from requests>=2.27.1->pycaret) (3.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/being/Library/Python/3.9/lib/python/site-packages (from requests>=2.27.1->pycaret) (2023.7.22)
Requirement already satisfied: scikit-base<0.6.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret) (0.5.2)
Requirement already satisfied: deprecated>=1.2.13 in /Users/being/Library/Python/3.9/lib/python/site-packages (from sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret) (1.2.14)
Requirement already satisfied: wrapt<2,>=1.10 in /Users/being/Library/Python/3.9/lib/python/site-packages (from deprecated>=1.2.13->sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1->pycaret) (1.15.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/being/Library/Python/3.9/lib/python/site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (3.11.0)
Requirement already satisfied: executing>=1.2.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=5.5.0->pycaret) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/being/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: pure-eval in /Users/being/Library/Python/3.9/lib/python/site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.2)
WARNING: You are using pip version 21.2.4; however, version 23.3.2 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [1]:
# 필요한 라이브러리 및 데이터 불러오기
import pandas as pd
from pycaret.classification import *

In [2]:
df = pd.read_csv("../data/train.csv")

In [3]:
df.columns

Index(['ID', '대출금액', '대출기간', '근로기간', '주택소유상태', '연간소득', '부채_대비_소득_비율', '총계좌수',
       '대출목적', '최근_2년간_연체_횟수', '총상환원금', '총상환이자', '총연체금액', '연체계좌수', '대출등급'],
      dtype='object')

In [4]:
# PyCaret 설정 및 데이터 로드
clf1 = setup(data=df, target='대출등급')

In [5]:
# 모델 비교 및 선택
best_model = compare_models()

In [6]:
# 모델 학습
final_model = create_model(best_model)

In [7]:
# 모델 튜닝
tuned_model = tune_model(final_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [8]:
# 모델 평가
evaluate_model(tuned_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [9]:
df_test = pd.read_csv("../data/test.csv")

In [11]:
# 모델 예측
predictions = predict_model(tuned_model, data=df_test)

# 마지막 결과 확인
print(predictions.head())

           ID      대출금액        대출기간     근로기간    주택소유상태       연간소득  \
0  TEST_00000  16800000   36 months  8 years  MORTGAGE  132000000
1  TEST_00001   8400000   36 months  5 years      RENT   89971200
2  TEST_00002  17280000   36 months  6 years      RENT  150000000
3  TEST_00003  14400000   36 months  5 years  MORTGAGE   66000000
4  TEST_00004  27600000   36 months  5 years      RENT   55200000

   부채_대비_소득_비율  총계좌수   대출목적  최근_2년간_연체_횟수    총상환원금     총상환이자  총연체금액  연체계좌수  \
0    19.639999    12  주택 개선             0   394692  146604.0    0.0    0.0
1    15.840000    25  부채 통합             0        0       0.0    0.0    0.0
2     8.410000    20  신용 카드             0  1786980  281820.0    0.0    0.0
3    13.720000    30  신용 카드             1   669024  281724.0    0.0    0.0
4    30.500000    12  신용 카드             0  1250052  614844.0    0.0    0.0

  prediction_label  prediction_score
0                B            0.3771
1                A            0.3022
2                A            0.6067
3                B            0.3437
4                C            0.4229

In [12]:
predictions

,ID,대출금액,대출기간,근로기간,주택소유상태,연간소득,부채_대비_소득_비율,총계좌수,대출목적,최근_2년간_연체_횟수,총상환원금,총상환이자,총연체금액,연체계좌수,prediction_label,prediction_score
0,TEST_00000,16800000,36 months,8 years,MORTGAGE,132000000,19.639999,12,주택 개선,0,394692,146604.0,0.0,0.0,B,0.3771
1,TEST_00001,8400000,36 months,5 years,RENT,89971200,15.840000,25,부채 통합,0,0,0.0,0.0,0.0,A,0.3022
2,TEST_00002,17280000,36 months,6 years,RENT,150000000,8.410000,20,신용 카드,0,1786980,281820.0,0.0,0.0,A,0.6067
3,TEST_00003,14400000,36 months,5 years,MORTGAGE,66000000,13.720000,30,신용 카드,1,669024,281724.0,0.0,0.0,B,0.3437
4,TEST_00004,27600000,36 months,5 years,RENT,55200000,30.500000,12,신용 카드,0,1250052,614844.0,0.0,0.0,C,0.4229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64192,TEST_64192,30000000,36 months,3 years,MORTGAGE,78000000,22.080000,27,부채 통합,2,1307532,763380.0,0.0,0.0,C,0.4979
64193,TEST_64193,30000000,60 months,10+ years,MORTGAGE,109200000,12.060000,26,부채 통합,0,960612,1245252.0,0.0,0.0,D,0.3969
64194,TEST_64194,6120000,36 months,10+ years,RENT,39600000,28.799999,33,부채 통합,0,131520,80880.0,0.0,0.0,C,0.2302
64195,TEST_64195,11520000,36 months,10+ years,MORTGAGE,66000000,25.440001,41,부채 통합,1,1339536,601872.0,0.0,0.0,C,0.4301
64196,TEST_64196,6000000,36 months,9 years,RENT,180000000,9.070000,10,부채 통합,0,308880,48960.0,0.0,0.0,A,0.4111

In [13]:
res = pd.read_csv("../data/sample_submission.csv")
res

               ID 대출등급
0      TEST_00000    G
1      TEST_00001    G
2      TEST_00002    G
3      TEST_00003    G
4      TEST_00004    G
...           ...  ...
64192  TEST_64192    G
64193  TEST_64193    G
64194  TEST_64194    G
64195  TEST_64195    G
64196  TEST_64196    G

[64197 rows x 2 columns]

In [15]:
res['대출등급'] = predictions['prediction_label']

In [16]:
res

               ID 대출등급
0      TEST_00000    B
1      TEST_00001    A
2      TEST_00002    A
3      TEST_00003    B
4      TEST_00004    C
...           ...  ...
64192  TEST_64192    C
64193  TEST_64193    D
64194  TEST_64194    C
64195  TEST_64195    C
64196  TEST_64196    A

[64197 rows x 2 columns]

In [18]:
res.to_csv("../res/res_submission.csv", index=False)